languageCode = "en-US"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "RRogers"
copyright = "Copyright &copy; 2024 - Randolph Rogers"

[params]
  dateFormat = "2 January 2006"
  mainSections = ["blog"]
# description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."

[params.author]
  name = "Randolph Rogers"
  image = "img/author.jpg"
  headline = "In data we trust..."
  #bio = "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
  links = [
#    { x-twitter = "https://twitter.com/" },
#    { facebook = "https://facebook.com/" },
    { linkedin = "https://linkedin.com/in/randolphrogers/" },
    { github = "https://github.com/SwattyX" },
#    { youtube = "https://youtube.com/" },
  ]