languageCode = "es-MX"
languageName = "Español"
languageDirection = "ltr"
weight = 2

title = "RRogers"
copyright = "Copyright &copy; 2024 - Randolph Rogers"

[params]
  dateFormat = "2 January 2006"
  mainSections = ["blog"]
# description = "Un tema poderoso y liviano para Hugo creado con Tailwind CSS."

[params.author]
  name = "Randolph Rogers"
  image = "img/author.jpg"
  headline = "¿Que dicen los datos?"
  #bio = "Esta es una biografía de autor de ejemplo, y aunque aquí hay una foto de un perro, este artículo en realidad fue creado por un ser humano. :dog:"
  links = [
#    { x-twitter = "https://twitter.com/" },
#    { facebook = "https://facebook.com/" },
    { linkedin = "https://linkedin.com/in/randolphrogers/" },
    { github = "https://github.com/SwattyX" },
#    { youtube = "https://youtube.com/" },
  ]